#!/usr/bin/env bash

## Copyright (C) 2020-2022 Aditya Shakya <adi1090x@gmail.com>

## Set GTK Themes, Icons, Cursor and Fonts

THEME='Tokyonight-Dark-BL'
ICONS='Papirus-Dark'
FONT='华康手札体W7-A 12'
CURSOR='Afterglow-Recolored-Catppuccin-Blue-v3'
CUROSO_SIZE='32'

SCHEMA='gsettings set org.gnome.desktop.interface'

${SCHEMA} gtk-theme "$THEME"
${SCHEMA} icon-theme "$ICONS"
${SCHEMA} cursor-theme "$CURSOR"
${SCHEMA} font-name "$FONT"
${SCHEMA} cursor-size "$CUROSO_SIZE"
