# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, pkgs, lib, modulesPath, ... }:
let
  btrfsRootDevice =
    "/dev/disk/by-partuuid/e045af97-09b2-40ad-a689-6112fba55097";
in {
  imports = [ (modulesPath + "/installer/scan/not-detected.nix") ];

  boot = {
    initrd.availableKernelModules =
      [ "xhci_pci" "ahci" "nvme" "usbhid" "uas" "sd_mod" ];
    initrd.kernelModules = [ ];
    extraModulePackages = [ ];
  };

  systemd.services.nix-daemon = {
    environment.TMPDIR = "/var/cache/nix";
    serviceConfig.CacheDirectory = "nix";
  };
  environment.variables.NIX_REMOTE = "daemon";

  fileSystems = {
    "/" = {
      device = "tmpfs";
      fsType = "tmpfs";
      options = [ "relatime" "mode=755" ];
    };
    "/nix" = {
      device = btrfsRootDevice;
      fsType = "btrfs";
      options = [ "subvol=nix" ];
    };
    "/var" = {
      device = btrfsRootDevice;
      fsType = "btrfs";
      options = [ "subvol=var" ];
    };
    "/boot" = {
      device = btrfsRootDevice;
      fsType = "btrfs";
      options = [ "subvol=boot" ];
    };
    "/home" = {
      device = btrfsRootDevice;
      fsType = "btrfs";
      options = [ "subvol=home" ];
    };
    "/root" = {
      device = "/home/root";
      options = [ "bind" ];
    };
    "/boot/efi" = {
      device = "/dev/disk/by-partuuid/003d291d-141e-f045-9f0a-0afba7158ae7";
      fsType = "vfat";
      options = [ "fmask=0022" "dmask=0022" ];
    };
  };

  environment.etc = {
    "nixos".source = "/nix/persist/etc/nixos";
    "machine-id".source = "/nix/persist/etc/machine-id";
  };

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode =
    lib.mkDefault config.hardware.enableRedistributableFirmware;
}
