#!/usr/bin/env bash

## Copyright (C) 2020-2022 Aditya Shakya <adi1090x@gmail.com>

## Script To Manage Speaker Volume For Archcraft (in Wayland).

iDIR="$HOME/.config/hypr/icons"

# Get Volume
get_volume() {
    volume=$(amixer get Master | tail -n1 | awk -F ' ' '{print $5}' | tr -d '[]')
    echo "$volume"
}

# Get icons
get_icon() {
    vol="$(get_volume)"
    current="${vol%%%}"
    if amixer get Master | grep '\[on\]' &>/dev/null; then
        if (("$current" == 0)); then
            icon="$iDIR/volume_off.svg"
        elif (("$current" < 33)); then
            icon="$iDIR/volume_low.svg"
        elif (("$current" < 66)); then
            icon="$iDIR/volume_medium.svg"
        else
            icon="$iDIR/volume_high.svg"
        fi
    else
        icon="$iDIR/volume_muted.svg"
    fi
}

# Notify
notify_user() {
    notify-send -i "$icon" -u normal -h string:x-dunst-stack-tag:volume -a "Volume" "Volume at $(get_volume)"
}

# Increase Volume
inc_volume() {
    for _ in $(seq 5); do
        amixer -Mq set Master,0 1%+ && get_icon && notify_user
        sleep 0.000001
    done
}

# Decrease Volume
dec_volume() {
    for _ in $(seq 5); do
        amixer -Mq set Master,0 1%- && get_icon && notify_user
        sleep 0.000001
    done
}

# Toggle Mute
toggle_mute() {
    amixer set Master toggle && get_icon && notify_user
}

# Execute accordingly
if [[ "$1" == "--get" ]]; then
    get_volume
elif [[ "$1" == "--inc" ]]; then
    inc_volume
elif [[ "$1" == "--dec" ]]; then
    dec_volume
elif [[ "$1" == "--toggle" ]]; then
    toggle_mute
else
    get_volume
fi
