local ICONS = {
  dap = {
    Stopped = {
      "󰁕 ",
      "DiagnosticWarn",
      "DapStoppedLine",
    },
    Breakpoint = " ",
    BreakpointCondition = "󰘥 ",
    BreakpointRejected = {
      " ",
      "DiagnosticError",
    },
    LogPoint = ".>",
  },
  diagnostics = {
    Error = " ",
    Warn = " ",
    Hint = " ",
    Info = " ",
  },
  git = {
    added = " ",
    modified = " ",
    removed = " ",
  },
  kinds = {
    Array = " ",
    Boolean = " ",
    BreakStatement = "󰙧 ",
    Call = "󰃷 ",
    CaseStatement = "󱃙 ",
    Class = "󰠱 ",
    Codeium = "󰘦 ",
    Color = " ",
    Constant = "󰏿 ",
    Constructor = " ",
    ContinueStatement = "→ ",
    Copilot = " ",
    Declaration = "󰙠 ",
    Delete = "󰩺 ",
    DoStatement = "󰑖 ",
    Eent = " ",
    Emoji = "󰇴 ",
    Enum = " ",
    EnumMember = " ",
    Event = " ",
    Field = " ",
    File = "󰧮 ",
    Folder = " ",
    Fonts = " ",
    ForStatement = "󰑖 ",
    Function = "󰡱 ",
    H1Marker = "󰉫 ",
    H2Marker = "󰉬 ",
    H3Marker = "󰉭 ",
    H4Marker = "󰉮 ",
    H5Marker = "󰉯 ",
    H6Marker = "󰉰 ",
    Identifier = "󰀫 ",
    IfStatement = "󰇉 ",
    Interface = " ",
    Key = " ",
    Keyword = "󰌋 ",
    List = " ",
    Log = "󰦪 ",
    Lsp = " ",
    Macro = "󰁌 ",
    MarkdownH1 = "󰉫 ",
    MarkdownH2 = "󰉬 ",
    MarkdownH3 = "󰉭 ",
    MarkdownH4 = "󰉮 ",
    MarkdownH5 = "󰉯 ",
    MarkdownH6 = "󰉰 ",
    Method = "󰆧 ",
    Module = " ",
    Namespace = " ",
    NerdFont = " ",
    Null = "󰢤 ",
    Number = " ",
    Object = " ",
    Operator = "󰆕 ",
    Package = "󰏖 ",
    Pair = " ",
    Property = "󰜢 ",
    Reference = " ",
    Regex = " ",
    Repeat = "󰑖 ",
    Scope = " ",
    Snippet = " ",
    Specifier = "󰦪 ",
    Statement = " ",
    String = " ",
    Struct = " ",
    SwitchStatement = "󰺟 ",
    Text = "󰧭 ",
    Type = " ",
    TypeParameter = "󰅲 ",
    Unit = "󰑭 ",
    Value = "󰎠 ",
    Variable = "󰂡 ",
    WhileStatement = "󰑖 ",
  },
}

return {
  "Buer-Nahida/LazyVim",
  opts = { icons = ICONS },
}
