password: ENC[AES256_GCM,data:/C0A9kxOVo+qTT6xUGvWiOOU7sFZn8p1E6ISJh5vjzZLx967AdCeEkr5i7mg5628P0Xm2lErvEEAp3hfG/1H4yuYFcVPdvvvGQ==,iv:zC/vIk4XzQh0qtl/UwxsfYPC3pHjwYawqF2w68WRzNw=,tag:yUYH8yamDAOXjAtdOLfrcg==,type:str]
nix: ENC[AES256_GCM,data:eCsg2BhlXhQBozFfK6Oo5tOnzshZD28kJjZ1REHJXwCaZOgE1+bVKvyEDtAGAF0B5CYk86VR68ZHvhZUWBEdKqdAgw==,iv:6vo3iGOKgIf3Jujp0wz+52nAYrkEJbe5cPaLAU0EhMM=,tag:P5s69mh+quEb2JLCPI6CnA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1hjgyy0u35dccc24kv8sa37vc2twr5vupmgwec8eregte84ltjdaqvu95aa
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIblhCbEdka3BHVVFpTURh
            TmhoSmtXR0RtdzVyN0RSb2oxUldpekJwSFZ3ClJVV2xJbnZ3WFAydys5Z1RQOUgz
            eCttSkM0WG1CQ1FYME0rcVNORUtJN2sKLS0tIGtLK29aanhJdlhURTQweGJ5MGJw
            VTJhS0IyUlpmdmZXQWxvVzMvb3Fsbm8KTeSvCjTUQ6n/vV/mm0MGMXxUO5fDhAPg
            wCQOq6StCVzEEJVQ9YF0J/fH64nY2+I9lHQgzDzZ0T43UxYiatWr3g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-11-23T07:54:04Z"
    mac: ENC[AES256_GCM,data:MfnGKfI/SCiB5Vg7EdYST/Kicn/spGyIB2gCfrZcVI83pyLoYU75OeuAGWaR1uih8JG3rwBFgoPzTLNT4BY9J6NHBb0ME2SoH9f0WF5eVHL6Nhxu/9SCqHqmtbGh2iafi9kI9kuCTXiEAbYWIyBki/13bLRkVs1Dw4IRZiLiZzg=,iv:c5Uy8NNdooeMR7OsqHe6ojcgcZJC6lagJcNNO3w7BUE=,tag:xCwKWNU1kuOHCH1rG6qIOQ==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.1
