nix: ENC[AES256_GCM,data:eCsg2BhlXhQBozFfK6Oo5tOnzshZD28kJjZ1REHJXwCaZOgE1+bVKvyEDtAGAF0B5CYk86VR68ZHvhZUWBEdKqdAgw==,iv:6vo3iGOKgIf3Jujp0wz+52nAYrkEJbe5cPaLAU0EhMM=,tag:P5s69mh+quEb2JLCPI6CnA==,type:str]
password: ENC[AES256_GCM,data:/C0A9kxOVo+qTT6xUGvWiOOU7sFZn8p1E6ISJh5vjzZLx967AdCeEkr5i7mg5628P0Xm2lErvEEAp3hfG/1H4yuYFcVPdvvvGQ==,iv:zC/vIk4XzQh0qtl/UwxsfYPC3pHjwYawqF2w68WRzNw=,tag:yUYH8yamDAOXjAtdOLfrcg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1hjgyy0u35dccc24kv8sa37vc2twr5vupmgwec8eregte84ltjdaqvu95aa
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIblhCbEdka3BHVVFpTURh
            TmhoSmtXR0RtdzVyN0RSb2oxUldpekJwSFZ3ClJVV2xJbnZ3WFAydys5Z1RQOUgz
            eCttSkM0WG1CQ1FYME0rcVNORUtJN2sKLS0tIGtLK29aanhJdlhURTQweGJ5MGJw
            VTJhS0IyUlpmdmZXQWxvVzMvb3Fsbm8KTeSvCjTUQ6n/vV/mm0MGMXxUO5fDhAPg
            wCQOq6StCVzEEJVQ9YF0J/fH64nY2+I9lHQgzDzZ0T43UxYiatWr3g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-11-10T09:42:05Z"
    mac: ENC[AES256_GCM,data:uw1ecDE6eR6UNFG1dw8Guv4ZuBtry79X3S3tP8eCTqGziybDTwPYWAqBWGbEbKLtnm/F/vPxcnXdkdgniMR+jI2EwPyrgWdzZwniAEvRFXRlIKxqralDTdPqC64g91vYP9++DJsndzm2t7ZwPY8jCMpcfm2degD9RkoiWGIQonU=,iv:UJU6L6G3y1WLXoo4AjYauPSoByRdlAYHJIwtSg5Mra4=,tag:IaDMrg1FbVcZO85uaqxXDA==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.1
