{
	"data": "ENC[AES256_GCM,data:bsPLoJgDugHThsQfUBJQ7m4lqaM1glt+/qWEHRjC6kyzqGsV6ruHb9yizlRkvoAj/2no9TwxsbWx7lGsr81txi37Rzj8z+ENEVHHjh4ooZdZJniwECOF+yMn6MqvdfScCSkl9gaJ1GZFj5ZUWkmW8mznG0QnDe1f7qpyw/ljvSVNLZORXIs6jlyp3LOMX4t8Y8V26f6Fr019iv/qBBoN6Z51fLbx0FS2Vy0pyX+HIvs3ehGpXn1CsdNMCUMkQVmFCvQ2Lfgi4A0BXO8mJHizFHagR8tSMK5fE1B2j2sy2EK9lKa/lK57InPKz4oYGUXtX/3s,iv:ddD3fcp26LHAmSmRzLPVpi4mxqmED66CvdG7q+9g6Xk=,tag:nRxtWNAodywXTTJ4/kq+wA==,type:str]",
	"sops": {
		"kms": null,
		"gcp_kms": null,
		"azure_kv": null,
		"hc_vault": null,
		"age": [
			{
				"recipient": "age1hjgyy0u35dccc24kv8sa37vc2twr5vupmgwec8eregte84ltjdaqvu95aa",
				"enc": "-----BEGIN AGE ENCRYPTED FILE-----\nYWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAycWt2TE0wMlB2OVN5OTFD\naWdidkJWNlVOcEN4RXZ1OXhnTGtzZFlFTmdJCkVuNVJGcnBMaVZvSkUrRHNjNFBN\naVhHQ0lCV3Irb2ZYOWkvbXh0RzRnQnMKLS0tIDJWWExWNTFObnBVWUxjNzlSa1FD\nSjd6c0laYy9abHYyUUtlTG05N3BlMjAKRoz2xaR2WdY94GpeUWFdSvfvDJxuMZAd\nQN3FmGbJ4GtVCSF9QVOknes5XdcOMhzTATNxYhOMgGXPOuYEzWVneQ==\n-----END AGE ENCRYPTED FILE-----\n"
			}
		],
		"lastmodified": "2025-02-16T02:18:23Z",
		"mac": "ENC[AES256_GCM,data:IWqvwS3GMgGe7aFfVzBKKCs0Q2pahrBclT39Odc/Lf2dY0hkTwst8xV1XBtYaavHzbbMynyA8zsGj/Pht7fFxtyHLGDJrM4OX+2Oiw7wQoEdpw0wzMg1yp1/lm8Nx3x6jym9Dw4psbusKxvsv99pYFuln8od6Ixpr5qL0FyATzQ=,iv:YP5l+YEkhp4Yt9EpER9bXEXwMlGtRFnwXjLH9EX+O3o=,tag:2aJpmA6EK+T2ecBZ5NLwPQ==,type:str]",
		"pgp": null,
		"unencrypted_suffix": "_unencrypted",
		"version": "3.9.4"
	}
}